go:
    version: 1.14
repository:
    path: github.com/stackhpc/jiralert
build:
    binaries:
        - name: jiralert
          path: cmd/jiralert 
    flags: -a -tags netgo
crossbuild:
    platforms:
        - linux/amd64
